version: "3.7"
services:
  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

#   https://hub.docker.com/_/postgres
  postgres:
    image: mdillon/postgis:11-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    restart: always
    volumes:
    - type: bind
      source: ./init-postgres.sql
      target: /docker-entrypoint-initdb.d/init-postgres.sql

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379